--- /root/Dockerfile.s390x_gobuild_old	2020-01-06 10:45:27.094864285 +0000
+++ Dockerfile.s390x	2020-01-06 10:46:14.154894241 +0000
@@ -54,8 +54,9 @@
 RUN go get github.com/onsi/ginkgo/ginkgo
 
 # Install linting tools.
-RUN wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
-RUN golangci-lint --version
+RUN go get -u gopkg.in/alecthomas/gometalinter.v2
+RUN ln -s `which gometalinter.v2` /usr/local/bin/gometalinter
+RUN gometalinter --install
 
 # Install license checking tool.
 RUN go get github.com/pmezard/licenses
